### ISSUE TITLE
Breaks reactivity

### ISSUE THREAD

**Issue by mesqueeb** [phanan/vue-linkify#5]
When I use this plugin on a DIV which has something like
```html
<div v-linkified>{{ item.summary }}</div>
```
the vue-linkify plugin breaks reactivity of Vue.
**When I update item.summary it is not reflected in the div.**

How can I best fix this?

**Comment by benoitliard** [comment]
You are probably not using the v-html to fill your value.

**Comment by mesqueeb** [comment]
@benoitliard you were right!!! Thank you so much.
